services:
  reverse-proxy:
    image: traefik:v3.2
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.dnschallenge=true"
      - "--certificatesresolvers.myresolver.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.myresolver.acme.email=heyanantraj@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    labels:
      - "traefik.http.middlewares.test-ratelimit.ratelimit.average=100"
      - "traefik.http.middlewares.test-ratelimit.ratelimit.burst=200"
      - "traefik.http.middlewares.test-compress.compress=true"
      - "traefik.http.middlewares.test-compress.compress.defaultEncoding=gzip"
      - "traefik.http.middlewares.test-compress.compress.encodings=gzip,zstd,br"
      - "traefik.http.middlewares.test-retry.retry.attempts=4"
      - "traefik.http.middlewares.test-retry.retry.initialinterval=100ms"
    ports:
      - "80:80"
      - "443:443"
    secrets:
      - CF_DNS_API_TOKEN
    environment:
      - CF_DNS_API_TOKEN_FILE=/run/secrets/CF_DNS_API_TOKEN
    volumes:
      - letsencrypt:/letsencrypt
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  tutorme:
    image: ghcr.io/tutorme-verse/tutorme-backend:${GIT_COMMIT_HASH:-latest}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tutorme.rule=Host(`api.tutorme.tech`) || HostRegexp(`{subdomain:[a-z]+}.tutorme.tech`)"
      - "traefik.http.routers.tutorme.entrypoints=websecure"
      - "traefik.http.routers.tutorme.tls.certresolver=myresolver"
      - "traefik.http.services.tutorme.loadbalancer.server.port=3000"
    deploy:
      mode: replicated
      replicas: 3
    secrets:
      - TURSO_DATABASE_URL
      - TURSO_API_TOKEN
      - TURSO_AUTH_TOKEN
      - TURSO_ORGANIZATION_SLUG
      - GO_ENV
      - DOCKER_PORT
      - CF_API_TOKEN
      - CF_API_EMAIL
      - CF_ZONE_ID
    environment:
      - TURSO_DATABASE_URL_FILE=/run/secrets/TURSO_DATABASE_URL
      - TURSO_AUTH_TOKEN_FILE=/run/secrets/TURSO_AUTH_TOKEN
      - TURSO_API_TOKEN_FILE=/run/secrets/TURSO_API_TOKEN
      - TURSO_ORGANIZATION_SLUG_FILE=/run/secrets/TURSO_ORGANIZATION_SLUG
      - GO_ENV_FILE=/run/secrets/GO_ENV
      - DOCKER_PORT_FILE=/run/secrets/DOCKER_PORT
      - CF_API_TOKEN_FILE=/run/secrets/CF_API_TOKEN
      - CF_API_EMAIL_FILE=/run/secrets/CF_API_EMAIL
      - CF_ZONE_ID_FILE=/run/secrets/CF_ZONE_ID
volumes:
  letsencrypt:

secrets:
  CF_DNS_API_TOKEN:
    external: true
  CF_API_TOKEN:
    external: true
  CF_API_EMAIL:
    external: true
  CF_ZONE_ID:
    external: true
  DOCKER_PORT:
    external: true
  GO_ENV:
    external: true
  TURSO_AUTH_TOKEN:
    external: true
  TURSO_DATABASE_URL:
    external: true
  TURSO_ORGANIZATION_SLUG:
    external: true
  TURSO_API_TOKEN:
    external: true
