services:
  reverse-proxy:
    image: traefik:v3.2
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.dnschallenge=true"
      - "--certificatesresolvers.myresolver.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.myresolver.acme.email=heyanantraj@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    secrets:
      - CF_DNS_API_TOKEN
    environment:
      - CF_DNS_API_TOKEN_FILE=/run/secrets/CF_DNS_API_TOKEN
    volumes:
      - letsencrypt:/letsencrypt
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  tutorme:
    image: anant2raj/tutorme:0.0.5
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tutorme.rule=Host(`api.tutorme.tech`)"
      - "traefik.http.routers.tutorme.entrypoints=websecure"
      - "traefik.http.routers.tutorme.tls.certresolver=myresolver"
      - "traefik.http.services.tutorme.loadbalancer.server.port=3000"
    deploy:
      mode: replicated
      replicas: 3
    expose:
      - 3000
    secrets:
      - TURSO_DATABASE_URL
      - TURSO_AUTH_TOKEN
      - GO_ENV
      - DOCKER_PORT
    environment:
      - TURSO_DATABASE_URL_FILE=/run/secrets/TURSO_DATABASE_URL
      - TURSO_AUTH_TOKEN_FILE=/run/secrets/TURSO_AUTH_TOKEN
      - GO_ENV_FILE=/run/secrets/GO_ENV
      - DOCKER_PORT_FILE=/run/secrets/DOCKER_PORT
volumes:
  letsencrypt:

secrets:
  CF_DNS_API_TOKEN:
    external: true
  DOCKER_PORT:
    external: true
  GO_ENV:
    external: true
  TURSO_AUTH_TOKEN:
    external: true
  TURSO_DATABASE_URL:
    external: true
