services:
  app:
    build:
      context: .
      target: ${GO_ENV}
    container_name: tutorme
    environment:
      TURSO_DATABASE_URL: ${TURSO_DATABASE_URL}
      TURSO_AUTH_TOKEN: ${TURSO_AUTH_TOKEN}
      GO_ENV: ${GO_ENV}
      APP_PORT: ${APP_PORT}
      DOCKER_PORT: ${DOCKER_PORT}
    env_file:
      - ./.env
    ports:
      - ${DOCKER_PORT}:${APP_PORT}
    volumes:
      - .:/app
