// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"database/sql"
)

type DatabaseDetail struct {
	DatabaseID        int64        `json:"database_id"`
	ForeignDatabaseID string       `json:"foreign_database_id"`
	SchoolID          int64        `json:"school_id"`
	DatabaseName      string       `json:"database_name"`
	ConnectionUri     string       `json:"connection_uri"`
	CreatedAt         sql.NullTime `json:"created_at"`
}

type School struct {
	SchoolID   int64        `json:"school_id"`
	SchoolName string       `json:"school_name"`
	Subdomain  string       `json:"subdomain"`
	CreatedAt  sql.NullTime `json:"created_at"`
	Status     string       `json:"status"`
}
